# Generated by Django 6.0 on 2025-12-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
